### ISSUE TITLE
Summary of issues discovered with GitHub Linguist release

### ISSUE THREAD

**Issue by Arcensoth** [Arcensoth/language-mcfunction#11]
The grammar module employed by [linguist](https://github.com/github/linguist) might simply be out-of-date, in which case some issues may be resolved upon the next release of linguist.

- [x] ~~NBT keys with non-alpha characters:~~ Fixed for next release; see #10 
  - https://github.com/Arcensoth/language-mcfunction/blob/master/tests/nbt_compound.mcfunction#L23
- [x] ~~Selectors scores with capital letters:~~ Fixed for next release; see #12
  - https://github.com/Arcensoth/language-mcfunction/blob/master/tests/selector.mcfunction#L155
- [x] ~~Selector argument whitespace:~~ Fixed for next release; see #13
  - https://github.com/Arcensoth/language-mcfunction/blob/master/tests/selector.mcfunction#L31
  - https://github.com/Arcensoth/language-mcfunction/blob/master/tests/selector.mcfunction#L58
- [x] ~~Trailing argument is invalid without newline:~~ Fixed for next release; see #14
  - https://github.com/MinecraftPhi/MinecraftPhi-modules/blob/master/phi.core/src/datapack/data/phi.core/functions/internal/load.mcfunction#L14

**Comment by Arcensoth** [comment]
All fixed; ready for next release.

**Comment by Arcensoth** [comment]
Fixes are in as of v0.11.0 and should be live on GitHub as soon as the next [linguist](https://github.com/github/linguist) release is out.
